[package]
name = "eave-dev"
version = "0.1.0"
authors = ["Eave Protocol"]
edition = "2018"

[[bin]]
name = "eave-dev"
path = "src/main.rs"

[dependencies]
futures = "0.3.4"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }
eave-dev-cli = { path = "cli" }
eave-dev-service = { path = "service" }

[features]
runtime-benchmarks = [
	"eave-dev-cli/runtime-benchmarks",
]
with-ethereum-compatibility = [
	"eave-dev-service/with-ethereum-compatibility"
]
with-steam-runtime = []
