[package]
name = "eave-dev-service"
version = "0.1.0"
authors = ["Eave Protocol"]
edition = "2018"

[dependencies]
hex-literal = "0.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}

sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

module-evm = { path = "../../../ecosystem-pallets/aca/modules/evm" }
module-evm-rpc-runtime-api = { path = "../../../ecosystem-pallets/aca/modules/evm/rpc/runtime_api" }
module-staking-pool = { path = "../../../ecosystem-pallets/aca/modules/staking-pool" }
module-staking-pool-rpc = { path = "../../../ecosystem-pallets/aca/modules/staking-pool/rpc" }
module-nft = { path = "../../../ecosystem-pallets/aca/modules/nft" }
orml-oracle-rpc = { path = "../../../ecosystem-pallets/orml/oracle/rpc" }
acala-primitives = { path = '../../../ecosystem-pallets/aca/primitives', default-features = false }
eave-rpc = { path = "../../../rpc", features = ["standalone"]}

eave-runtime-common = { path = "../../../runtime/common" }
steam-runtime = { path = "../../../runtime/steam", features = ["standalone"], optional = true }
eave-runtime = { path = "../../../runtime/eave", optional = true }

[dev-dependencies]
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[features]
default = ["std", "with-steam-runtime"]
std = []
runtime-benchmarks = [
	"steam-runtime/runtime-benchmarks",
	"eave-runtime/runtime-benchmarks",
]
with-steam-runtime = [
	"steam-runtime",
	"steam-runtime/standalone",
]
with-eave-runtime = [
	"eave-runtime",
]
with-all-runtime = [
	"with-steam-runtime",
	"with-eave-runtime",
]
with-ethereum-compatibility = [
	"steam-runtime/with-ethereum-compatibility"
]
