[package]
name = "eave-service"
version = "0.1.0"
authors = ["Eave Prtocol"]
edition = "2018"

[dependencies]
async-trait = { version = "0.1.48" }
hex-literal = "0.3.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
futures = "0.3.15"
codec = { package = "parity-scale-codec", version = "2.0.0" }

jsonrpc-core = "15.1.0"

sp-api = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }

sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions"}
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }

sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "rh-v0.9.5-missing-companions" }

cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-client-consensus-relay-chain = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.5" }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.5" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.5" }

# local dependencies
orml-oracle-rpc = { path = "../../ecosystem-pallets/orml/oracle/rpc" }

ecosystem-renvm-bridge = { path = "../../ecosystem-pallets/ren/renvm-bridge" }

acala-primitives = { path = '../../ecosystem-pallets/aca/primitives', default-features = false }
module-collator-selection = { path = "../../ecosystem-pallets/aca/modules/collator-selection" }
module-evm = { path = "../../ecosystem-pallets/aca/modules/evm", default-features = false }
module-evm-rpc-runtime-api = { path = "../../ecosystem-pallets/aca/modules/evm/rpc/runtime_api", default-features = false }
module-nft = { path = "../../ecosystem-pallets/aca/modules/nft" }
module-staking-pool = { path = '../../ecosystem-pallets/aca/modules/staking-pool', default-features = false }
module-staking-pool-rpc = { path = '../../ecosystem-pallets/aca/modules/staking-pool/rpc', default-features = false }

eave-rpc = { path = "../../rpc" }


eave-runtime-common = { path = "../../runtime/common" }
steam-runtime = { path = "../../runtime/steam", optional = true }
eave-runtime = { path = "../../runtime/eave", optional = true }

[features]
default = ["std"]
std = []
runtime-benchmarks = [
	"steam-runtime/runtime-benchmarks",
	"eave-runtime/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
]
try-runtime = [
	"steam-runtime/try-runtime",
	"eave-runtime/try-runtime",
	"polkadot-service/try-runtime",
]
with-steam-runtime = [
	"steam-runtime",
]
with-eave-runtime = [
	"eave-runtime",
]
with-all-runtime = [
	"with-steam-runtime",
	"with-eave-runtime",
]
