[package]
name = "eave-dev-cli"
version = "0.1.0"
authors = ["Eave Protocol"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }

inspect = { package = "eave-inspect", path = "../../../inspect" }
service = { package = "eave-dev-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[features]
default = [ "wasmtime", "cli", "with-dawn-runtime" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
with-dawn-runtime = [
	"service/with-dawn-runtime",
]
with-eave-runtime = [
	"service/with-eave-runtime",
]
with-all-runtime = [
	"service/with-all-runtime",
]
