[package]
name = "eave-cli"
version = "0.1.0"
authors = ["Eave Protocol"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
codec = { package = "parity-scale-codec", version = "2.0.0" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2", optional = true}
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2", optional = true }

cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.2" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.2" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.2" }


inspect = { package = "eave-inspect", path = "../../../inspect" }
service = { package = "eave-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.2", default-features = false }

[features]
default = [ "wasmtime", "cli", "with-steam-runtime" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
with-steam-runtime = [
	"service/with-steam-runtime",
]

with-eave-runtime = [
	"service/with-eave-runtime",
]

with-all-runtime = [
	"service/with-all-runtime",
]
